export const columns = [
  { id: "airline", label: "Airline" },
  { id: "sector", label: "Sector" },
  { id: "airlineNo", label: "Airline No." },
  { id: "returnAirlineNo", label: "Return Airline No." },
  { id: "departureDate", label: "Departure Date" },
  { id: "returnDate", label: "Return Date" },
  { id: "departureTime", label: "Departure Time" },
  { id: "arrivalTime", label: "Arrival Time" },
  { id: "quantity", label: "Quantity" },
  { id: "available", label: "Available" },
  { id: "sold", label: "Sold" },
  { id: "pnr", label: "PNR" },
  { id: "purchase", label: "Purchase" },
  { id: "price", label: "Price" },
  { id: "infant", label: "Infant" },
  { id: "action", label: "Action" },
];
