interface IAirlineList {
    IATA: string;
    ICAO: string;
    Name: string;
}

export const airlineList: IAirlineList[] = [
  {
    IATA: "A2",
    ICAO: "CIU",
    Name: "Cielos Airlines",
  },
  {
    IATA: "A3",
    ICAO: "AEE",
    Name: "Aegean Airlines",
  },
  {
    IATA: "A4",
    ICAO: "SWD",
    Name: "Southern Winds Airlines",
  },
  {
    IATA: "A5",
    ICAO: "HOP",
    Name: "Air France Hop",
  },
  {
    IATA: "A6",
    ICAO: "LPV",
    Name: "Air Alps Aviation",
  },
  {
    IATA: "A7",
    ICAO: "MPD",
    Name: "Air Plus Comet",
  },
  {
    IATA: "A8",
    ICAO: "AMF",
    Name: "Ameriflight",
  },
  {
    IATA: "A9",
    ICAO: "TGZ",
    Name: "Georgian Airways",
  },
  {
    IATA: "AA",
    ICAO: "AAL",
    Name: "American Airlines",
  },
  {
    IATA: "AB",
    ICAO: "BER",
    Name: "Air Berlin",
  },
  {
    IATA: "AC",
    ICAO: "ACA",
    Name: "Air Canada",
  },
  {
    IATA: "AD",
    ICAO: "AZU",
    Name: "Azul Linhas Aéreas Brasileiras",
  },
  {
    IATA: "AE",
    ICAO: "MDA",
    Name: "Mandarin Airlines",
  },
  {
    IATA: "AF",
    ICAO: "AFR",
    Name: "Air France",
  },
  {
    IATA: "AG",
    ICAO: "ABR",
    Name: "ASL Airlines Ireland",
  },
  {
    IATA: "AH",
    ICAO: "DAH",
    Name: "Air Algérie",
  },
  {
    IATA: "AI",
    ICAO: "AIC",
    Name: "Air India",
  },
  {
    IATA: "AJ",
    ICAO: "NIG",
    Name: "Aero Contractors",
  },
  {
    IATA: "AK",
    ICAO: "AXM",
    Name: "AirAsia",
  },
  {
    IATA: "AL",
    ICAO: "TXC",
    Name: "Transaviaexport",
  },
  {
    IATA: "AL",
    ICAO: "SYX",
    Name: "Skywalk Airlines",
  },
  {
    IATA: "AM",
    ICAO: "AMX",
    Name: "Aeroméxico",
  },
  {
    IATA: "AN",
    ICAO: "WSN",
    Name: "Advanced Air",
  },
  {
    IATA: "AO",
    ICAO: "AUZ",
    Name: "Australian Airlines",
  },
  {
    IATA: "AP",
    ICAO: "ADH",
    Name: "Air One",
  },
  {
    IATA: "AP",
    ICAO: "AIB",
    Name: "Airbus Industrie",
  },
  {
    IATA: "AR",
    ICAO: "ARG",
    Name: "Aerolíneas Argentinas",
  },
  {
    IATA: "AS",
    ICAO: "ASA",
    Name: "Alaska Airlines",
  },
  {
    IATA: "AT",
    ICAO: "RAM",
    Name: "Royal Air Maroc",
  },
  {
    IATA: "AU",
    ICAO: "AUT",
    Name: "Austral Lineas Aereas",
  },
  {
    IATA: "AV",
    ICAO: "AVA",
    Name: "Avianca",
  },
  {
    IATA: "AW",
    ICAO: "SCH",
    Name: "CHC Airways",
  },
  {
    IATA: "AW",
    ICAO: "DIR",
    Name: "Dirgantara Air Service",
  },
  {
    IATA: "AX",
    ICAO: "LOF",
    Name: "Trans States Airlines",
  },
  {
    IATA: "AY",
    ICAO: "FIN",
    Name: "Finnair",
  },
  {
    IATA: "AZ",
    ICAO: "ITY",
    Name: "ITA Airways",
  },
  {
    IATA: "B2",
    ICAO: "BRU",
    Name: "Belavia Belarusian Airlines",
  },
  {
    IATA: "B3",
    ICAO: "BLV",
    Name: "Bellview Airlines",
  },
  {
    IATA: "B4",
    ICAO: "GSM",
    Name: "Flyglobespan",
  },
  {
    IATA: "B4",
    ICAO: "BCF",
    Name: "BACH Flugbetriebsges",
  },
  {
    IATA: "B4",
    ICAO: "BKA",
    Name: "Bankair",
  },
  {
    IATA: "B5",
    ICAO: "EXZ",
    Name: "East African Safari Air Express",
  },
  {
    IATA: "B6",
    ICAO: "JBU",
    Name: "JetBlue",
  },
  {
    IATA: "B7",
    ICAO: "UIA",
    Name: "Uni Airways",
  },
  {
    IATA: "B8",
    ICAO: "ERT",
    Name: "Eritrean Airlines",
  },
  {
    IATA: "B9",
    ICAO: "BGD",
    Name: "Air Bangladesh",
  },
  {
    IATA: "BA",
    ICAO: "BAW",
    Name: "British Airways",
  },
  {
    IATA: "BB",
    ICAO: "SBS",
    Name: "Seaborne Airlines",
  },
  {
    IATA: "BC",
    ICAO: "SKY",
    Name: "Skymark Airlines",
  },
  {
    IATA: "BE",
    ICAO: "BEE",
    Name: "Flybe",
  },
  {
    IATA: "BF",
    ICAO: "RSR",
    Name: "Aero-Service",
  },
  {
    IATA: "BF",
    ICAO: "BBD",
    Name: "Bluebird Cargo",
  },
  {
    IATA: "BG",
    ICAO: "BBC",
    Name: "Biman Bangladesh Airlines",
  },
  {
    IATA: "BI",
    ICAO: "RBA",
    Name: "Royal Brunei Airlines",
  },
  {
    IATA: "BJ",
    ICAO: "LBT",
    Name: "Nouvel Air Tunisie",
  },
  {
    IATA: "BK",
    ICAO: "PDC",
    Name: "Potomac Air",
  },
  {
    IATA: "BL",
    ICAO: "PIC",
    Name: "Jetstar Pacific",
  },
  {
    IATA: "BM",
    ICAO: "BMR",
    Name: "bmi regional",
  },
  {
    IATA: "BN",
    ICAO: "HZA",
    Name: "Horizon Airlines",
  },
  {
    IATA: "BN",
    ICAO: "BNF",
    Name: "Braniff International Airways",
  },
  {
    IATA: "BO",
    ICAO: "BOU",
    Name: "Bouraq Indonesia Airlines",
  },
  {
    IATA: "BP",
    ICAO: "BOT",
    Name: "Air Botswana",
  },
  {
    IATA: "BQ",
    ICAO: "BKV",
    Name: "Bukovyna Airlines",
  },
  {
    IATA: "BR",
    ICAO: "EVA",
    Name: "EVA Air",
  },
  {
    IATA: "BS",
    ICAO: "BIH",
    Name: "British International Helicopters",
  },
  {
    IATA: "BT",
    ICAO: "BTI",
    Name: "airBaltic",
  },
  {
    IATA: "BU",
    ICAO: "CNO",
    Name: "SAS Braathens",
  },
  {
    IATA: "BV",
    ICAO: "BPA",
    Name: "Blue Panorama Airlines",
  },
  {
    IATA: "BW",
    ICAO: "BWA",
    Name: "Caribbean Airlines",
  },
  {
    IATA: "BX",
    ICAO: "ABL",
    Name: "Air Busan",
  },
  {
    IATA: "BY",
    ICAO: "TOM",
    Name: "TUI Airways",
  },
  {
    IATA: "BZ",
    ICAO: "BDA",
    Name: "Blue Dart Aviation",
  },
  {
    IATA: "BZ",
    ICAO: "KEE",
    Name: "Keystone Air Services",
  },
  {
    IATA: "C0",
    ICAO: "CLW",
    Name: "Centralwings",
  },
  {
    IATA: "C4",
    ICAO: "IMX",
    Name: "Zimex Aviation",
  },
  {
    IATA: "C5",
    ICAO: "UCA",
    Name: "CommutAir",
  },
  {
    IATA: "C6",
    ICAO: "CJA",
    Name: "CanJet",
  },
  {
    IATA: "C7",
    ICAO: "RLE",
    Name: "Rico Linhas Aéreas",
  },
  {
    IATA: "C9",
    ICAO: "RUS",
    Name: "Cirrus Airlines",
  },
  {
    IATA: "CA",
    ICAO: "CCA",
    Name: "Air China",
  },
  {
    IATA: "CC",
    ICAO: "ABD",
    Name: "Air Atlanta Icelandic",
  },
  {
    IATA: "CE",
    ICAO: "NTW",
    Name: "Nationwide Airlines",
  },
  {
    IATA: "CF",
    ICAO: "CYZ",
    Name: "China Postal Airlines",
  },
  {
    IATA: "CG",
    ICAO: "TOK",
    Name: "Airlines PNG",
  },
  {
    IATA: "CH",
    ICAO: "BMJ",
    Name: "Bemidji Airlines",
  },
  {
    IATA: "CI",
    ICAO: "CAL",
    Name: "China Airlines",
  },
  {
    IATA: "CJ",
    ICAO: "CBF",
    Name: "China Northern Airlines",
  },
  {
    IATA: "CJ",
    ICAO: "CFE",
    Name: "Cityflyer Express",
  },
  {
    IATA: "CK",
    ICAO: "CKK",
    Name: "China Cargo Airlines",
  },
  {
    IATA: "CL",
    ICAO: "CLH",
    Name: "Lufthansa CityLine",
  },
  {
    IATA: "CM",
    ICAO: "CMP",
    Name: "Copa Airlines",
  },
  {
    IATA: "CN",
    ICAO: "GDC",
    Name: "Grand China Air",
  },
  {
    IATA: "CO",
    ICAO: "COA",
    Name: "Continental Airlines",
  },
  {
    IATA: "CP",
    ICAO: "CPZ",
    Name: "Compass Airlines",
  },
  {
    IATA: "CQ",
    ICAO: "EXL",
    Name: "Sunshine Express Airlines",
  },
  {
    IATA: "CS",
    ICAO: "CMI",
    Name: "Continental Micronesia",
  },
  {
    IATA: "CT",
    ICAO: "CYL",
    Name: "Alitalia CityLiner",
  },
  {
    IATA: "CU",
    ICAO: "CUB",
    Name: "Cubana de Aviación",
  },
  {
    IATA: "CV",
    ICAO: "CLX",
    Name: "Cargolux",
  },
  {
    IATA: "CW",
    ICAO: "CWM",
    Name: "Air Marshall Islands",
  },
  {
    IATA: "CX",
    ICAO: "CPA",
    Name: "Cathay Pacific",
  },
  {
    IATA: "CY",
    ICAO: "CYP",
    Name: "Cyprus Airways",
  },
  {
    IATA: "CZ",
    ICAO: "CSN",
    Name: "China Southern Airlines",
  },
  {
    IATA: "D3",
    ICAO: "DAO",
    Name: "Daallo Airlines",
  },
  {
    IATA: "D4",
    ICAO: "LID",
    Name: "Alidaunia",
  },
  {
    IATA: "D5",
    ICAO: "DAU",
    Name: "Dauair",
  },
  {
    IATA: "D6",
    ICAO: "ILN",
    Name: "Interair South Africa",
  },
  {
    IATA: "D7",
    ICAO: "XFA",
    Name: "FlyAsianXpress",
  },
  {
    IATA: "D7",
    ICAO: "RDN",
    Name: "Dinar",
  },
  {
    IATA: "D8",
    ICAO: "IBK",
    Name: "Norwegian Air International",
  },
  {
    IATA: "D9",
    ICAO: "DNV",
    Name: "Aeroflot-Don",
  },
  {
    IATA: "DA",
    ICAO: "GRG",
    Name: "Air Georgia",
  },
  {
    IATA: "DB",
    ICAO: "BZH",
    Name: "Brit Air",
  },
  {
    IATA: "DC",
    ICAO: "GAO",
    Name: "Golden Air",
  },
  {
    IATA: "DD",
    ICAO: "NOK",
    Name: "Nok Air",
  },
  {
    IATA: "DE",
    ICAO: "CFG",
    Name: "condor",
  },
  {
    IATA: "DG",
    ICAO: "SRQ",
    Name: "Tigerair Philippines",
  },
  {
    IATA: "DH",
    ICAO: "NAN",
    Name: "Norwegian Air Norway",
  },
  {
    IATA: "DI",
    ICAO: "BAG",
    Name: "dba",
  },
  {
    IATA: "DJ",
    ICAO: "PLB",
    Name: "Polynesian Blue",
  },
  {
    IATA: "DJ",
    ICAO: "PBN",
    Name: "Pacific Blue",
  },
  {
    IATA: "DK",
    ICAO: "VKG",
    Name: "Thomas Cook Airlines Scandinavia",
  },
  {
    IATA: "DL",
    ICAO: "DAL",
    Name: "Delta Air Lines",
  },
  {
    IATA: "DP",
    ICAO: "FCA",
    Name: "First Choice Airways",
  },
  {
    IATA: "DR",
    ICAO: "BIE",
    Name: "Air Méditerranée",
  },
  {
    IATA: "DS",
    ICAO: "EZS",
    Name: "easyJet Switzerland",
  },
  {
    IATA: "DT",
    ICAO: "DTA",
    Name: "TAAG Angola Airlines",
  },
  {
    IATA: "DU",
    ICAO: "NLH",
    Name: "Norwegian Long Haul",
  },
  {
    IATA: "DV",
    ICAO: "ACK",
    Name: "Nantucket Airlines",
  },
  {
    IATA: "DW",
    ICAO: "UCR",
    Name: "Aero-Charter Ukraine",
  },
  {
    IATA: "DX",
    ICAO: "DTR",
    Name: "DAT Danish Air Transport",
  },
  {
    IATA: "DY",
    ICAO: "NAX",
    Name: "Norwegian Air Shuttle",
  },
  {
    IATA: "E0",
    ICAO: "ESS",
    Name: "Eos Airlines",
  },
  {
    IATA: "E2",
    ICAO: "KMP",
    Name: "Kampuchea Airlines",
  },
  {
    IATA: "E2",
    ICAO: "GRN",
    Name: "Rio Grande Air",
  },
  {
    IATA: "E3",
    ICAO: "DMO",
    Name: "Domodedovo Airlines",
  },
  {
    IATA: "E4",
    ICAO: "RSO",
    Name: "Aero Asia International",
  },
  {
    IATA: "E5",
    ICAO: "BRZ",
    Name: "Samara Airlines",
  },
  {
    IATA: "E7",
    ICAO: "ESF",
    Name: "Estafeta Carga Aerea",
  },
  {
    IATA: "E7",
    ICAO: "EAF",
    Name: "European Aviation Air Charter",
  },
  {
    IATA: "E8",
    ICAO: "ELG",
    Name: "Alpi Eagles",
  },
  {
    IATA: "E9",
    ICAO: "CXS",
    Name: "Boston-Maine Airways",
  },
  {
    IATA: "EC",
    ICAO: "EJU",
    Name: "easyJet Europe",
  },
  {
    IATA: "ED",
    ICAO: "ABQ",
    Name: "Airblue",
  },
  {
    IATA: "EE",
    ICAO: "EAY",
    Name: "Aero Airlines",
  },
  {
    IATA: "EF",
    ICAO: "EFA",
    Name: "Far Eastern Air Transport",
  },
  {
    IATA: "EG",
    ICAO: "JAA",
    Name: "Japan Asia Airways",
  },
  {
    IATA: "EH",
    ICAO: "AKX",
    Name: "ANA Wings",
  },
  {
    IATA: "EI",
    ICAO: "EIN",
    Name: "Aer Lingus",
  },
  {
    IATA: "EJ",
    ICAO: "NEA",
    Name: "New England Airlines",
  },
  {
    IATA: "EK",
    ICAO: "UAE",
    Name: "Emirates",
  },
  {
    IATA: "EL",
    ICAO: "ANK",
    Name: "Air Nippon",
  },
  {
    IATA: "EM",
    ICAO: "CFS",
    Name: "Empire Airlines",
  },
  {
    IATA: "EN",
    ICAO: "DLA",
    Name: "Air Dolomiti",
  },
  {
    IATA: "EO",
    ICAO: "ALX",
    Name: "Hewa Bora Airways",
  },
  {
    IATA: "EO",
    ICAO: "LHN",
    Name: "Express One International",
  },
  {
    IATA: "EP",
    ICAO: "IRC",
    Name: "Iran Aseman Airlines",
  },
  {
    IATA: "EQ",
    ICAO: "TAE",
    Name: "TAME",
  },
  {
    IATA: "ER",
    ICAO: "DHL",
    Name: "Astar Air Cargo",
  },
  {
    IATA: "ES",
    ICAO: "DHX",
    Name: "DHL International",
  },
  {
    IATA: "ET",
    ICAO: "ETH",
    Name: "Ethiopian Airlines",
  },
  {
    IATA: "EU",
    ICAO: "EEA",
    Name: "Ecuatoriana",
  },
  {
    IATA: "EV",
    ICAO: "ASQ",
    Name: "ExpressJet",
  },
  {
    IATA: "EW",
    ICAO: "EWG",
    Name: "Eurowings",
  },
  {
    IATA: "EX",
    ICAO: "SDO",
    Name: "Air Santo Domingo",
  },
  {
    IATA: "EY",
    ICAO: "ETD",
    Name: "Etihad Airways",
  },
  {
    IATA: "EZ",
    ICAO: "SUS",
    Name: "Sun Air of Scandinavia",
  },
  {
    IATA: "EZ",
    ICAO: "EIA",
    Name: "Evergreen International Airlines",
  },
  {
    IATA: "F2",
    ICAO: "FLM",
    Name: "Fly Air",
  },
  {
    IATA: "F3",
    ICAO: "FSW",
    Name: "Faso Airways",
  },
  {
    IATA: "F4",
    ICAO: "NBK",
    Name: "Albarka Air",
  },
  {
    IATA: "F5",
    ICAO: "COZ",
    Name: "Cosmic Air",
  },
  {
    IATA: "F6",
    ICAO: "RCK",
    Name: "Faroejet",
  },
  {
    IATA: "F7",
    ICAO: "BBO",
    Name: "Flybaboo",
  },
  {
    IATA: "F9",
    ICAO: "FFT",
    Name: "Frontier Airlines",
  },
  {
    IATA: "FA",
    ICAO: "SFR",
    Name: "Safair",
  },
  {
    IATA: "FB",
    ICAO: "LZB",
    Name: "Bulgaria Air",
  },
  {
    IATA: "FC",
    ICAO: "WBA",
    Name: "Finncomm Airlines",
  },
  {
    IATA: "FD",
    ICAO: "AIQ",
    Name: "Thai AirAsia",
  },
  {
    IATA: "FE",
    ICAO: "WCP",
    Name: "Primaris Airlines",
  },
  {
    IATA: "FG",
    ICAO: "AFG",
    Name: "Ariana Afghan Airlines",
  },
  {
    IATA: "FH",
    ICAO: "FHY",
    Name: "Freebird Airlines",
  },
  {
    IATA: "FI",
    ICAO: "ICE",
    Name: "Icelandair",
  },
  {
    IATA: "FJ",
    ICAO: "FJI",
    Name: "Fiji Airways",
  },
  {
    IATA: "FK",
    ICAO: "WTA",
    Name: "Africa West",
  },
  {
    IATA: "FL",
    ICAO: "TRS",
    Name: "AirTran Airways",
  },
  {
    IATA: "FM",
    ICAO: "CSH",
    Name: "Shanghai Airlines",
  },
  {
    IATA: "FO",
    ICAO: "ATM",
    Name: "Airlines Of Tasmania",
  },
  {
    IATA: "FP",
    ICAO: "FRE",
    Name: "Freedom Air",
  },
  {
    IATA: "FR",
    ICAO: "RYR",
    Name: "Ryanair",
  },
  {
    IATA: "FS",
    ICAO: "FOX",
    Name: "Flyr",
  },
  {
    IATA: "FT",
    ICAO: "SRH",
    Name: "Siem Reap Airways",
  },
  {
    IATA: "FV",
    ICAO: "PLK",
    Name: "Pulkovo Aviation Enterprise",
  },
  {
    IATA: "FV",
    ICAO: "SDM",
    Name: "Rossiya",
  },
  {
    IATA: "FW",
    ICAO: "IBX",
    Name: "Ibex Airlines",
  },
  {
    IATA: "FX",
    ICAO: "FDX",
    Name: "FedEx Express",
  },
  {
    IATA: "FY",
    ICAO: "NWR",
    Name: "Northwest Regional Airlines",
  },
  {
    IATA: "FY",
    ICAO: "FFM",
    Name: "Firefly",
  },
  {
    IATA: "FZ",
    ICAO: "FDB",
    Name: "Flydubai",
  },
  {
    IATA: "G0",
    ICAO: "GHB",
    Name: "Ghana International Airlines",
  },
  {
    IATA: "G2",
    ICAO: "VXG",
    Name: "Avirex",
  },
  {
    IATA: "G3",
    ICAO: "GLO",
    Name: "GOL Linhas Aéreas Inteligentes",
  },
  {
    IATA: "G4",
    ICAO: "AAY",
    Name: "Allegiant Air",
  },
  {
    IATA: "G5",
    ICAO: "HXA",
    Name: "China Express Airlines",
  },
  {
    IATA: "G6",
    ICAO: "BSR",
    Name: "Guine Bissaur Airlines",
  },
  {
    IATA: "G7",
    ICAO: "GJS",
    Name: "GoJet Airlines",
  },
  {
    IATA: "G8",
    ICAO: "GOW",
    Name: "GoAir",
  },
  {
    IATA: "G9",
    ICAO: "ABY",
    Name: "Air Arabia",
  },
  {
    IATA: "GA",
    ICAO: "GIA",
    Name: "Garuda Indonesia",
  },
  {
    IATA: "GB",
    ICAO: "ABX",
    Name: "ABX Air",
  },
  {
    IATA: "GC",
    ICAO: "GNR",
    Name: "Gambia International Airlines",
  },
  {
    IATA: "GD",
    ICAO: "AHA",
    Name: "Air Alpha Greenland",
  },
  {
    IATA: "GE",
    ICAO: "TNA",
    Name: "TransAsia Airways",
  },
  {
    IATA: "GF",
    ICAO: "GFA",
    Name: "Gulf Air",
  },
  {
    IATA: "GG",
    ICAO: "HAH",
    Name: "Air Comores International",
  },
  {
    IATA: "GG",
    ICAO: "GUY",
    Name: "Air Guyane",
  },
  {
    IATA: "GG",
    ICAO: "GGC",
    Name: "Cargo 360",
  },
  {
    IATA: "GH",
    ICAO: "GHA",
    Name: "Ghana Airways",
  },
  {
    IATA: "GI",
    ICAO: "LHA",
    Name: "Longhao Airlines",
  },
  {
    IATA: "GJ",
    ICAO: "EEU",
    Name: "Eurofly Service",
  },
  {
    IATA: "GJ",
    ICAO: "MXC",
    Name: "Compania Mexicargo",
  },
  {
    IATA: "GK",
    ICAO: "JJP",
    Name: "Jetstar Japan",
  },
  {
    IATA: "GL",
    ICAO: "BSK",
    Name: "Miami Air International",
  },
  {
    IATA: "GL",
    ICAO: "GRL",
    Name: "Air Greenland",
  },
  {
    IATA: "GM",
    ICAO: "SVK",
    Name: "Air Slovakia",
  },
  {
    IATA: "GN",
    ICAO: "AGN",
    Name: "Air Gabon",
  },
  {
    IATA: "GO",
    ICAO: "KZU",
    Name: "Kuzu Airlines Cargo",
  },
  {
    IATA: "GP",
    ICAO: "GES",
    Name: "Gestair",
  },
  {
    IATA: "GP",
    ICAO: "PTP",
    Name: "Palau Trans Pacific Airline",
  },
  {
    IATA: "GQ",
    ICAO: "BSY",
    Name: "Big Sky Airlines",
  },
  {
    IATA: "GR",
    ICAO: "AUR",
    Name: "Aurigny Air Services",
  },
  {
    IATA: "GR",
    ICAO: "GCO",
    Name: "Gemini Air Cargo",
  },
  {
    IATA: "GS",
    ICAO: "GCR",
    Name: "Tianjin Airlines",
  },
  {
    IATA: "GT",
    ICAO: "GBL",
    Name: "GB Airways",
  },
  {
    IATA: "GV",
    ICAO: "GUN",
    Name: "Grant Aviation",
  },
  {
    IATA: "GW",
    ICAO: "KIL",
    Name: "Kuban Airlines",
  },
  {
    IATA: "GX",
    ICAO: "JXX",
    Name: "Jetx Airlines",
  },
  {
    IATA: "GY",
    ICAO: "TMG",
    Name: "Tri-MG Intra Asia Airlines",
  },
  {
    IATA: "GZ",
    ICAO: "RAR",
    Name: "Rotation International Air Services",
  },
  {
    IATA: "H2",
    ICAO: "SKU",
    Name: "Sky Airline",
  },
  {
    IATA: "H5",
    ICAO: "MVL",
    Name: "Mavial Magadan Airlines",
  },
  {
    IATA: "H5",
    ICAO: "HOA",
    Name: "Hola Airlines",
  },
  {
    IATA: "H6",
    ICAO: "HAG",
    Name: "Hageland Aviation Services",
  },
  {
    IATA: "H8",
    ICAO: "KHB",
    Name: "Dalavia",
  },
  {
    IATA: "H9",
    ICAO: "IZM",
    Name: "Izair",
  },
  {
    IATA: "HA",
    ICAO: "HAL",
    Name: "Hawaiian Airlines",
  },
  {
    IATA: "HB",
    ICAO: "HGB",
    Name: "Greater Bay Airlines",
  },
  {
    IATA: "HC",
    ICAO: "ATI",
    Name: "Aero-Tropics Air Services",
  },
  {
    IATA: "HD",
    ICAO: "ADO",
    Name: "Air Do",
  },
  {
    IATA: "HE",
    ICAO: "LGW",
    Name: "Luftfahrtgesellschaft Walter",
  },
  {
    IATA: "HG",
    ICAO: "NLY",
    Name: "Niki",
  },
  {
    IATA: "HJ",
    ICAO: "AXF",
    Name: "Asian Express Airlines",
  },
  {
    IATA: "HK",
    ICAO: "FSC",
    Name: "Four Star Cargo",
  },
  {
    IATA: "HM",
    ICAO: "SEY",
    Name: "Air Seychelles",
  },
  {
    IATA: "HN",
    ICAO: "HVY",
    Name: "Heavylift Cargo Airlines",
  },
  {
    IATA: "HO",
    ICAO: "DKH",
    Name: "Juneyao Airlines",
  },
  {
    IATA: "HP",
    ICAO: "HPA",
    Name: "Pearl Airways",
  },
  {
    IATA: "HQ",
    ICAO: "TCW",
    Name: "Thomas Cook Airlines Belgium",
  },
  {
    IATA: "HR",
    ICAO: "HHN",
    Name: "Hahn Air",
  },
  {
    IATA: "HT",
    ICAO: "AHW",
    Name: "Aeromist-Kharkiv",
  },
  {
    IATA: "HU",
    ICAO: "CHH",
    Name: "Hainan Airlines",
  },
  {
    IATA: "HV",
    ICAO: "TRA",
    Name: "Transavia",
  },
  {
    IATA: "HW",
    ICAO: "NWL",
    Name: "North-Wright Airways",
  },
  {
    IATA: "HW",
    ICAO: "FHE",
    Name: "Hello",
  },
  {
    IATA: "HX",
    ICAO: "CRK",
    Name: "Hong Kong Airlines",
  },
  {
    IATA: "HY",
    ICAO: "UZB",
    Name: "Uzbekistan Airways",
  },
  {
    IATA: "HZ",
    ICAO: "SOZ",
    Name: "Sat Airlines",
  },
  {
    IATA: "I2",
    ICAO: "IBS",
    Name: "Iberia Express",
  },
  {
    IATA: "I4",
    ICAO: "FWA",
    Name: "Interstate Airline",
  },
  {
    IATA: "I5",
    ICAO: "IAD",
    Name: "AirAsia India",
  },
  {
    IATA: "I6",
    ICAO: "SEQ",
    Name: "Sky Eyes",
  },
  {
    IATA: "I7",
    ICAO: "PMW",
    Name: "Paramount Airways",
  },
  {
    IATA: "I9",
    ICAO: "HLF",
    Name: "Central Airlines",
  },
  {
    IATA: "IA",
    ICAO: "IAW",
    Name: "Iraqi Airways",
  },
  {
    IATA: "IB",
    ICAO: "IBE",
    Name: "Iberia Airlines",
  },
  {
    IATA: "IC",
    ICAO: "IAC",
    Name: "Indian Airlines",
  },
  {
    IATA: "ID",
    ICAO: "ITK",
    Name: "Interlink Airlines",
  },
  {
    IATA: "IE",
    ICAO: "SOL",
    Name: "Solomon Airlines",
  },
  {
    IATA: "IF",
    ICAO: "ISW",
    Name: "Islas Airways",
  },
  {
    IATA: "IG",
    ICAO: "ISS",
    Name: "Air Italy",
  },
  {
    IATA: "II",
    ICAO: "CSQ",
    Name: "IBC Airways",
  },
  {
    IATA: "IJ",
    ICAO: "GWL",
    Name: "Great Wall Airlines",
  },
  {
    IATA: "IK",
    ICAO: "ITX",
    Name: "Imair Airlines",
  },
  {
    IATA: "IK",
    ICAO: "LKN",
    Name: "Lankair",
  },
  {
    IATA: "IM",
    ICAO: "MNJ",
    Name: "Menajet",
  },
  {
    IATA: "IN",
    ICAO: "MAK",
    Name: "MAT Macedonian Airlines",
  },
  {
    IATA: "IO",
    ICAO: "IAA",
    Name: "Indonesian Airlines",
  },
  {
    IATA: "IP",
    ICAO: "JOL",
    Name: "Atyrau Air Ways",
  },
  {
    IATA: "IQ",
    ICAO: "AUB",
    Name: "Augsburg Airways",
  },
  {
    IATA: "IR",
    ICAO: "IRA",
    Name: "Iran Air",
  },
  {
    IATA: "IT",
    ICAO: "TTW",
    Name: "Tigerair Taiwan",
  },
  {
    IATA: "IV",
    ICAO: "JET",
    Name: "Wind Jet",
  },
  {
    IATA: "IV",
    ICAO: "CPN",
    Name: "Caspian Airlines",
  },
  {
    IATA: "IW",
    ICAO: "AOM",
    Name: "AOM French Airlines",
  },
  {
    IATA: "IX",
    ICAO: "AXB",
    Name: "Air India Express",
  },
  {
    IATA: "IY",
    ICAO: "IYE",
    Name: "Yemenia",
  },
  {
    IATA: "IZ",
    ICAO: "AIZ",
    Name: "Arkia Israel Airlines",
  },
  {
    IATA: "J2",
    ICAO: "AHY",
    Name: "Azerbaijan Airlines",
  },
  {
    IATA: "J3",
    ICAO: "PLR",
    Name: "Northwestern Air",
  },
  {
    IATA: "J4",
    ICAO: "BFL",
    Name: "Buffalo Airways",
  },
  {
    IATA: "J6",
    ICAO: "VCR",
    Name: "Cruiser Linhas Aéreas",
  },
  {
    IATA: "J7",
    ICAO: "CVC",
    Name: "Centre-Avia",
  },
  {
    IATA: "J8",
    ICAO: "BVT",
    Name: "Berjaya Air",
  },
  {
    IATA: "J9",
    ICAO: "JZR",
    Name: "Jazeera Airways",
  },
  {
    IATA: "JB",
    ICAO: "JBA",
    Name: "Helijet",
  },
  {
    IATA: "JC",
    ICAO: "JEX",
    Name: "JAL Express",
  },
  {
    IATA: "JE",
    ICAO: "MNO",
    Name: "Mango",
  },
  {
    IATA: "JF",
    ICAO: "LAB",
    Name: "L.A.B. Flying Service",
  },
  {
    IATA: "JH",
    ICAO: "FDA",
    Name: "Fuji Dream Airlines",
  },
  {
    IATA: "JI",
    ICAO: "MDW",
    Name: "Midway Airlines",
  },
  {
    IATA: "JJ",
    ICAO: "AGX",
    Name: "Aviogenex",
  },
  {
    IATA: "JJ",
    ICAO: "TAM",
    Name: "TAM Brazilian Airlines",
  },
  {
    IATA: "JK",
    ICAO: "JKK",
    Name: "Spanair",
  },
  {
    IATA: "JL",
    ICAO: "JAL",
    Name: "Japan Airlines",
  },
  {
    IATA: "JM",
    ICAO: "AJM",
    Name: "Air Jamaica",
  },
  {
    IATA: "JN",
    ICAO: "XLA",
    Name: "Excel Airways",
  },
  {
    IATA: "JO",
    ICAO: "JAZ",
    Name: "JALways",
  },
  {
    IATA: "JP",
    ICAO: "ADR",
    Name: "Adria Airways",
  },
  {
    IATA: "JQ",
    ICAO: "JST",
    Name: "Jetstar Airways",
  },
  {
    IATA: "JR",
    ICAO: "SER",
    Name: "Aero California",
  },
  {
    IATA: "JT",
    ICAO: "LNI",
    Name: "Lion Air",
  },
  {
    IATA: "JU",
    ICAO: "JAT",
    Name: "Jat Airways",
  },
  {
    IATA: "JU",
    ICAO: "ASL",
    Name: "Air Serbia",
  },
  {
    IATA: "JV",
    ICAO: "BLS",
    Name: "Bearskin Lake Air Service",
  },
  {
    IATA: "JW",
    ICAO: "VNL",
    Name: "Vanilla Air",
  },
  {
    IATA: "JX",
    ICAO: "SJX",
    Name: "STARLUX Airlines",
  },
  {
    IATA: "JY",
    ICAO: "TCI",
    Name: "Air Turks and Caicos",
  },
  {
    IATA: "JZ",
    ICAO: "SKX",
    Name: "Skyways Express",
  },
  {
    IATA: "K2",
    ICAO: "ELO",
    Name: "Eurolot",
  },
  {
    IATA: "K4",
    ICAO: "CKS",
    Name: "Kalitta Air",
  },
  {
    IATA: "K5",
    ICAO: "ABE",
    Name: "Aban Air",
  },
  {
    IATA: "K5",
    ICAO: "WAK",
    Name: "Wings of Alaska",
  },
  {
    IATA: "K6",
    ICAO: "KZW",
    Name: "Khalifa Airways",
  },
  {
    IATA: "K8",
    ICAO: "ZAK",
    Name: "Airlink Zambia",
  },
  {
    IATA: "K9",
    ICAO: "KRI",
    Name: "Krylo Airlines",
  },
  {
    IATA: "KA",
    ICAO: "HDA",
    Name: "Cathay Dragon",
  },
  {
    IATA: "KB",
    ICAO: "DRK",
    Name: "Druk Air",
  },
  {
    IATA: "KC",
    ICAO: "KZR",
    Name: "Air Astana",
  },
  {
    IATA: "KD",
    ICAO: "WGN",
    Name: "Western Global Airlines",
  },
  {
    IATA: "KE",
    ICAO: "KAL",
    Name: "Korean Air",
  },
  {
    IATA: "KF",
    ICAO: "BLF",
    Name: "Blue1",
  },
  {
    IATA: "KG",
    ICAO: "LYM",
    Name: "Key Lime Air",
  },
  {
    IATA: "KH",
    ICAO: "AAH",
    Name: "Aloha Air Cargo",
  },
  {
    IATA: "KI",
    ICAO: "DHI",
    Name: "Adam Air",
  },
  {
    IATA: "KI",
    ICAO: "SKZ",
    Name: "Skyway Enterprises",
  },
  {
    IATA: "KJ",
    ICAO: "LAJ",
    Name: "British Mediterranean Airways",
  },
  {
    IATA: "KK",
    ICAO: "KKK",
    Name: "Atlasjet",
  },
  {
    IATA: "KL",
    ICAO: "KLM",
    Name: "KLM Royal Dutch Airlines",
  },
  {
    IATA: "KM",
    ICAO: "AMC",
    Name: "Air Malta",
  },
  {
    IATA: "KN",
    ICAO: "CUA",
    Name: "China United Airlines",
  },
  {
    IATA: "KO",
    ICAO: "AER",
    Name: "Alaska Central Express",
  },
  {
    IATA: "KP",
    ICAO: "KIA",
    Name: "Kiwi International Air Lines",
  },
  {
    IATA: "KQ",
    ICAO: "KQA",
    Name: "Kenya Airways",
  },
  {
    IATA: "KR",
    ICAO: "CWK",
    Name: "Comores Airlines",
  },
  {
    IATA: "KS",
    ICAO: "PEN",
    Name: "Peninsula Airways",
  },
  {
    IATA: "KU",
    ICAO: "KAC",
    Name: "Kuwait Airways",
  },
  {
    IATA: "KV",
    ICAO: "SKV",
    Name: "Sky Regional Airlines",
  },
  {
    IATA: "KX",
    ICAO: "CAY",
    Name: "Cayman Airways",
  },
  {
    IATA: "KZ",
    ICAO: "NCA",
    Name: "Nippon Cargo Airlines",
  },
  { IATA: "L1", ICAO: "TTL", Name: "Total Linhas Aéreas" },
  { IATA: "L2", ICAO: "LYC", Name: "Lynden Air Cargo" },
  { IATA: "L3", ICAO: "LTO", Name: "LTU Austria" },
  { IATA: "L3", ICAO: "JOS", Name: "DHL de Guatemala" },
  { IATA: "L5", ICAO: "LTR", Name: "Lufttransport" },
  { IATA: "L6", ICAO: "VNZ", Name: "Tbilaviamsheni" },
  { IATA: "L7", ICAO: "LPN", Name: "Laoag International Airlines" },
  { IATA: "L7", ICAO: "LNP", Name: "Linea Aerea SAPSA" },
  { IATA: "L8", ICAO: "LXG", Name: "Air Luxor GB" },
  { IATA: "L9", ICAO: "TLW", Name: "Teamline Air" },
  { IATA: "LA", ICAO: "LAN", Name: "LATAM Chile" },
  { IATA: "LB", ICAO: "LLB", Name: "Lloyd Aéreo Boliviano" },
  { IATA: "LD", ICAO: "TUY", Name: "Linea Turistica Aerotuy" },
  { IATA: "LD", ICAO: "AHK", Name: "Air Hong Kong" },
  { IATA: "LE", ICAO: "NSW", Name: "Norwegian Air Sweden" },
  { IATA: "LF", ICAO: "VTE", Name: "Contour Airlines" },
  { IATA: "LG", ICAO: "LGL", Name: "Luxair" },
  { IATA: "LH", ICAO: "DLH", Name: "Lufthansa" },
  { IATA: "LH", ICAO: "GEC", Name: "Lufthansa Cargo" },
  { IATA: "LI", ICAO: "LIA", Name: "Leeward Islands Air Transport" },
  { IATA: "LJ", ICAO: "JNA", Name: "Jin Air" },
  { IATA: "LK", ICAO: "LXR", Name: "Air Luxor" },
  { IATA: "LL", ICAO: "GRO", Name: "Allegro" },
  { IATA: "LN", ICAO: "LAA", Name: "Libyan Arab Airlines" },
  { IATA: "LO", ICAO: "LOT", Name: "LOT Polish Airlines" },
  { IATA: "LP", ICAO: "LPE", Name: "LAN Peru" },
  { IATA: "LQ", ICAO: "LAQ", Name: "Lebanese Air Transport" },
  { IATA: "LR", ICAO: "LRC", Name: "LACSA" },
  { IATA: "LS", ICAO: "EXS", Name: "Jet2.com" },
  { IATA: "LT", ICAO: "LTU", Name: "LTU International" },
  { IATA: "LU", ICAO: "LXP", Name: "LAN Express" },
  { IATA: "LV", ICAO: "LBC", Name: "Albanian Airlines" },
  { IATA: "LW", ICAO: "NMI", Name: "Pacific Wings" },
  { IATA: "LX", ICAO: "SWR", Name: "Swiss International Air Lines" },
  { IATA: "LY", ICAO: "ELY", Name: "El Al Israel Airlines" },
  { IATA: "LZ", ICAO: "LBY", Name: "Belle Air" },
  { IATA: "M2", ICAO: "MZS", Name: "Mahfooz Aviation" },
  { IATA: "M3", ICAO: "TUS", Name: "ABSA - Aerolinhas Brasileiras" },
  { IATA: "M3", ICAO: "SPJ", Name: "Air Service" },
  { IATA: "M3", ICAO: "NFA", Name: "North Flying" },
  { IATA: "M4", ICAO: "NOV", Name: "Nova Airline" },
  { IATA: "M5", ICAO: "KEN", Name: "Kenmore Air" },
  { IATA: "M6", ICAO: "AJT", Name: "Amerijet International" },
  { IATA: "M7", ICAO: "MAA", Name: "MasAir" },
  { IATA: "M9", ICAO: "MSI", Name: "Motor Sich" },
  { IATA: "MA", ICAO: "MAH", Name: "Malév Hungarian Airlines" },
  { IATA: "MB", ICAO: "MNB", Name: "MNG Airlines" },
  { IATA: "MC", ICAO: "RCH", Name: "Air Mobility Command" },
  { IATA: "MD", ICAO: "MDG", Name: "Air Madagascar" },
  { IATA: "ME", ICAO: "MEA", Name: "Middle East Airlines" },
  { IATA: "MF", ICAO: "CXA", Name: "XiamenAir" },
  { IATA: "MG", ICAO: "CCP", Name: "Champion Air" },
  { IATA: "MH", ICAO: "MAS", Name: "Malaysia Airlines" },
  { IATA: "MI", ICAO: "SLK", Name: "SilkAir" },
  { IATA: "MJ", ICAO: "LPR", Name: "Líneas Aéreas Privadas Argentinas" },
  { IATA: "MK", ICAO: "MAU", Name: "Air Mauritius" },
  { IATA: "MM", ICAO: "APJ", Name: "Peach" },
  { IATA: "MN", ICAO: "CAW", Name: "Comair" },
  { IATA: "MO", ICAO: "CAV", Name: "Calm Air" },
  { IATA: "MO", ICAO: "AUH", Name: "Abu Dhabi Amiri Flight" },
  { IATA: "MP", ICAO: "MPH", Name: "Martinair" },
  { IATA: "MQ", ICAO: "ENY", Name: "Envoy Air" },
  { IATA: "MQ", ICAO: "EGF", Name: "American Eagle Airlines" },
  { IATA: "MR", ICAO: "MRT", Name: "Air Mauritanie" },
  { IATA: "MS", ICAO: "MSR", Name: "EgyptAir" },
  { IATA: "MT", ICAO: "TCX", Name: "Thomas Cook Airlines" },
  { IATA: "MU", ICAO: "CES", Name: "China Eastern Airlines" },
  { IATA: "MV", ICAO: "RML", Name: "Armenian International Airways" },
  { IATA: "MW", ICAO: "MYD", Name: "Maya Island Air" },
  { IATA: "MX", ICAO: "MXA", Name: "Mexicana de Aviación" },
  { IATA: "MY", ICAO: "MWA", Name: "Midwest Airlines" },
  { IATA: "MZ", ICAO: "MNA", Name: "Merpati Nusantara Airlines" },
  { IATA: "N2", ICAO: "QNK", Name: "Kabo Air" },
  { IATA: "N2", ICAO: "DAG", Name: "Dagestan Airlines" },
  { IATA: "N3", ICAO: "OMS", Name: "Omskavia Airline" },
  { IATA: "N4", ICAO: "MTC", Name: "Mountain Air Company" },
  { IATA: "N5", ICAO: "SGY", Name: "Skagway Air Service" },
  { IATA: "N5", ICAO: "KGZ", Name: "Kyrgyz Airlines" },
  { IATA: "N6", ICAO: "ACQ", Name: "Nuevo Continente" },
  { IATA: "N6", ICAO: "LGA", Name: "Lagun Air" },
  { IATA: "N7", ICAO: "ROK", Name: "National Airlines" },
  { IATA: "N8", ICAO: "HGK", Name: "Fika Salaama Airlines" },
  { IATA: "N9", ICAO: "NVR", Name: "Novair" },
  { IATA: "NB", ICAO: "SNB", Name: "Sterling Airlines" },
  { IATA: "NC", ICAO: "NAC", Name: "Northern Air Cargo" },
  { IATA: "NC", ICAO: "NJS", Name: "National Jet Systems" },
  { IATA: "NE", ICAO: "ESK", Name: "SkyEurope" },
  { IATA: "NF", ICAO: "AVN", Name: "Air Vanuatu" },
  { IATA: "NG", ICAO: "LDA", Name: "Lauda Air" },
  { IATA: "NH", ICAO: "ANA", Name: "All Nippon Airways" },
  { IATA: "NI", ICAO: "PGA", Name: "Portugalia" },
  { IATA: "NK", ICAO: "NKS", Name: "Spirit Airlines" },
  { IATA: "NL", ICAO: "SAI", Name: "Shaheen Air International" },
  { IATA: "NM", ICAO: "DRD", Name: "Air Madrid" },
  { IATA: "NM", ICAO: "NZM", Name: "Mount Cook Airlines" },
  { IATA: "NN", ICAO: "MOV", Name: "VIM Airlines" },
  { IATA: "NO", ICAO: "NOS", Name: "Neos" },
  { IATA: "NO", ICAO: "AUS", Name: "Aus-Air" },
  { IATA: "NQ", ICAO: "AJX", Name: "Air Japan" },
  { IATA: "NR", ICAO: "PIR", Name: "Pamir Airways" },
  { IATA: "NT", ICAO: "IBB", Name: "Binter Canarias" },
  { IATA: "NU", ICAO: "JTA", Name: "Japan Transocean Air" },
  { IATA: "NV", ICAO: "CRF", Name: "Air Central" },
  { IATA: "NW", ICAO: "NWA", Name: "Northwest Airlines" },
  { IATA: "NX", ICAO: "AMU", Name: "Air Macau" },
  { IATA: "NY", ICAO: "FXI", Name: "Air Iceland" },
  { IATA: "NZ", ICAO: "ANZ", Name: "Air New Zealand" },
  { IATA: "O3", ICAO: "CSS", Name: "SF Airlines" },
  { IATA: "O6", ICAO: "ONE", Name: "Avianca Brazil" },
  { IATA: "O7", ICAO: "OZJ", Name: "Ozjet Airlines" },
  { IATA: "O8", ICAO: "OHK", Name: "Oasis Hong Kong Airlines" },
  { IATA: "OA", ICAO: "OAL", Name: "Olympic Airlines" },
  { IATA: "OB", ICAO: "ASZ", Name: "Astrakhan Airlines" },
  { IATA: "OD", ICAO: "MXD", Name: "Malindo Air" },
  { IATA: "OE", ICAO: "AOT", Name: "Asia Overnight Express" },
  { IATA: "OH", ICAO: "JIA", Name: "PSA Airlines" },
  { IATA: "OJ", ICAO: "OLA", Name: "Overland Airways" },
  { IATA: "OK", ICAO: "CSA", Name: "Czech Airlines" },
  { IATA: "OL", ICAO: "OLT", Name: "Ostfriesische Lufttransport" },
  { IATA: "OM", ICAO: "MGL", Name: "MIAT Mongolian Airlines" },
  { IATA: "OO", ICAO: "SKW", Name: "SkyWest Airlines" },
  { IATA: "OR", ICAO: "TFL", Name: "TUI fly Netherlands" },
  { IATA: "OS", ICAO: "AUA", Name: "Austrian Airlines" },
  { IATA: "OT", ICAO: "PEL", Name: "Aeropelican Air Services" },
  { IATA: "OU", ICAO: "CTN", Name: "Croatia Airlines" },
  { IATA: "OV", ICAO: "ELL", Name: "Estonian Air" },
  { IATA: "OW", ICAO: "EXK", Name: "Executive Airlines" },
  { IATA: "OX", ICAO: "OEA", Name: "Orient Thai Airlines" },
  { IATA: "OY", ICAO: "OAE", Name: "Omni Air International" },
  { IATA: "OZ", ICAO: "AAR", Name: "Asiana Airlines" },
  { IATA: "P5", ICAO: "RPB", Name: "Copa Airlines Colombia" },
  { IATA: "P7", ICAO: "ESL", Name: "Russian Sky Airlines" },
  { IATA: "P9", ICAO: "PGP", Name: "Perm Airlines" },
  { IATA: "PA", ICAO: "FCL", Name: "Florida Coastal Airlines" },
  { IATA: "PC", ICAO: "PGT", Name: "Pegasus Airlines" },
  { IATA: "PD", ICAO: "POE", Name: "Porter Airlines" },
  { IATA: "PE", ICAO: "AEL", Name: "Air Europe" },
  { IATA: "PF", ICAO: "PNW", Name: "Palestinian Airlines" },
  { IATA: "PG", ICAO: "BKP", Name: "Bangkok Airways" },
  { IATA: "PH", ICAO: "PAO", Name: "Polynesian Airlines" },
  { IATA: "PJ", ICAO: "SPM", Name: "Air Saint Pierre" },
  { IATA: "PK", ICAO: "PIA", Name: "Pakistan International Airlines" },
  { IATA: "PL", ICAO: "PLI", Name: "Aeroperú" },
  { IATA: "PM", ICAO: "TOS", Name: "Tropic Air" },
  { IATA: "PO", ICAO: "PAC", Name: "Polar Air Cargo" },
  { IATA: "PQ", ICAO: "SQP", Name: "SkyUp" },
  { IATA: "PR", ICAO: "PAL", Name: "Philippine Airlines" },
  { IATA: "PS", ICAO: "AUI", Name: "Ukraine International Airlines" },
  { IATA: "PT", ICAO: "PDT", Name: "Piedmont Airlines" },
  { IATA: "PU", ICAO: "PUA", Name: "PLUNA" },
  { IATA: "PV", ICAO: "PNR", Name: "PAN Air" },
  { IATA: "PW", ICAO: "PRF", Name: "Precision Air" },
  { IATA: "PX", ICAO: "ANG", Name: "Air Niugini" },
  { IATA: "PY", ICAO: "SLM", Name: "Surinam Airways" },
  { IATA: "PZ", ICAO: "LAP", Name: "TAM Mercosur" },
  { IATA: "Q3", ICAO: "MBN", Name: "Zambian Airways" },
  { IATA: "Q5", ICAO: "MLA", Name: "40-Mile Air" },
  { IATA: "Q6", ICAO: "CDP", Name: "Aero Condor Peru" },
  { IATA: "Q8", ICAO: "PEC", Name: "Pacific East Asia Cargo Airlines" },
  { IATA: "Q9", ICAO: "AFU", Name: "Afrinat International Airlines" },
  { IATA: "QB", ICAO: "GFG", Name: "Georgian National Airlines" },
  { IATA: "QC", ICAO: "CRD", Name: "Air Corridor" },
  { IATA: "QE", ICAO: "ECC", Name: "Crossair Europe" },
  { IATA: "QF", ICAO: "QFA", Name: "Qantas" },
  { IATA: "QH", ICAO: "LYN", Name: "Air Kyrgyzstan" },
  { IATA: "QI", ICAO: "CIM", Name: "Cimber Air" },
  { IATA: "QK", ICAO: "JZA", Name: "Air Canada Jazz" },
  { IATA: "QL", ICAO: "RLN", Name: "Aero Lanka" },
  { IATA: "QM", ICAO: "AML", Name: "Air Malawi" },
  { IATA: "QN", ICAO: "ARR", Name: "Air Armenia" },
  { IATA: "QO", ICAO: "MPX", Name: "Aeromexpress" },
  { IATA: "QQ", ICAO: "UTY", Name: "Alliance Airlines" },
  { IATA: "QR", ICAO: "QTR", Name: "Qatar Airways" },
  { IATA: "QS", ICAO: "TVS", Name: "Smartwings" },
  { IATA: "QT", ICAO: "TPA", Name: "Tampa Cargo" },
  { IATA: "QV", ICAO: "LAO", Name: "Lao Airlines" },
  { IATA: "QW", ICAO: "BWG", Name: "Blue Wings" },
  { IATA: "QX", ICAO: "QXE", Name: "Horizon Air" },
  { IATA: "QY", ICAO: "BCS", Name: "European Air Transport Leipzig" },
  { IATA: "QZ", ICAO: "AWQ", Name: "Indonesia AirAsia" },
  { IATA: "R0", ICAO: "RPK", Name: "Royal Airlines" },
  { IATA: "R2", ICAO: "ORB", Name: "Orenburg Airlines" },
  { IATA: "R3", ICAO: "RME", Name: "Armenian Airlines" },
  { IATA: "R3", ICAO: "SYL", Name: "Aircompany Yakutia" },
  { IATA: "R5", ICAO: "JAV", Name: "Jordan Aviation" },
  { IATA: "R5", ICAO: "MAC", Name: "Malta Air Charter" },
  { IATA: "R7", ICAO: "OCA", Name: "Aserca Airlines" },
  { IATA: "R8", ICAO: "KGA", Name: "Kyrgyzstan Airlines" },
  { IATA: "R9", ICAO: "CAM", Name: "Camai Air" },
  { IATA: "RB", ICAO: "SYR", Name: "Syrian Arab Airlines" },
  { IATA: "RB", ICAO: "SBK", Name: "Air Srpska" },
  { IATA: "RC", ICAO: "FLI", Name: "Atlantic Airways" },
  { IATA: "RD", ICAO: "RYN", Name: "Ryan International Airlines" },
  { IATA: "RE", ICAO: "REA", Name: "Aer Arann" },
  { IATA: "RF", ICAO: "FWL", Name: "Florida West International Airways" },
  { IATA: "RG", ICAO: "VRN", Name: "VRG Linhas Aereas" },
  { IATA: "RH", ICAO: "RPH", Name: "Republic Express Airlines" },
  { IATA: "RI", ICAO: "MDL", Name: "Mandala Airlines" },
  { IATA: "RJ", ICAO: "RJA", Name: "Royal Jordanian" },
  { IATA: "RK", ICAO: "RKH", Name: "Royal Khmer Airlines" },
  { IATA: "RL", ICAO: "ABG", Name: "Royal Flight" },
  { IATA: "RO", ICAO: "ROT", Name: "Tarom" },
  { IATA: "RQ", ICAO: "KMF", Name: "Kam Air" },
  { IATA: "RR", ICAO: "RFR", Name: "Royal Air Force" },
  { IATA: "RS", ICAO: "MJN", Name: "Royal Air Force of Oman" },
  { IATA: "RT", ICAO: "RKM", Name: "RAK Airways" },
  { IATA: "RU", ICAO: "ABW", Name: "AirBridgeCargo" },
  { IATA: "RV", ICAO: "ROU", Name: "Air Canada Rouge" },
  { IATA: "RW", ICAO: "RPA", Name: "Republic Airlines" },
  { IATA: "RX", ICAO: "AEH", Name: "Aviaexpress" },
  { IATA: "S0", ICAO: "OKS", Name: "Slok Air Gambia" },
  { IATA: "S2", ICAO: "JLL", Name: "JetLite" },
  { IATA: "S3", ICAO: "BBR", Name: "Santa Barbara Airlines" },
  { IATA: "S4", ICAO: "RZO", Name: "SATA International" },
  { IATA: "S5", ICAO: "TSJ", Name: "Trast Aero" },
  { IATA: "S5", ICAO: "TCF", Name: "Shuttle America" },
  { IATA: "S7", ICAO: "SBI", Name: "S7 Airlines" },
  { IATA: "S8", ICAO: "SWW", Name: "Shovkoviy Shlyah" },
  { IATA: "S8", ICAO: "CSU", Name: "Chari Aviation Services" },
  { IATA: "SA", ICAO: "SAA", Name: "South African Airways" },
  { IATA: "SB", ICAO: "ACI", Name: "Air Caledonie International" },
  { IATA: "SC", ICAO: "CDG", Name: "Shandong Airlines" },
  { IATA: "SD", ICAO: "SUD", Name: "Sudan Airways" },
  { IATA: "SE", ICAO: "XLF", Name: "XL Airways France" },
  { IATA: "SF", ICAO: "DTH", Name: "Tassili Airlines" },
  { IATA: "SG", ICAO: "SEJ", Name: "SpiceJet" },
  { IATA: "SH", ICAO: "FLY", Name: "Fly Me Sweden" },
  { IATA: "SI", ICAO: "SIH", Name: "Skynet Airlines" },
  { IATA: "SJ", ICAO: "CGL", Name: "Seagle Air" },
  { IATA: "SK", ICAO: "SAS", Name: "Scandinavian Airlines" },
  { IATA: "SN", ICAO: "BEL", Name: "Brussels Airlines" },
  { IATA: "SO", ICAO: "OSL", Name: "Sosoliso Airlines" },
  { IATA: "SO", ICAO: "HKA", Name: "Superior Aviation" },
  { IATA: "SP", ICAO: "SAT", Name: "SATA Air Acores" },
  { IATA: "SQ", ICAO: "SIA", Name: "Singapore Airlines" },
  { IATA: "SQ", ICAO: "SQC", Name: "Singapore Airlines Cargo" },
  { IATA: "SS", ICAO: "CRL", Name: "Corsair International" },
  { IATA: "ST", ICAO: "GMI", Name: "Germania" },
  { IATA: "SU", ICAO: "AFL", Name: "Aeroflot" },
  { IATA: "SV", ICAO: "SVA", Name: "Saudi Arabian Airlines" },
  { IATA: "SW", ICAO: "NMB", Name: "Air Namibia" },
  { IATA: "SX", ICAO: "SKB", Name: "Skybus Airlines" },
  { IATA: "SY", ICAO: "SCX", Name: "Sun Country Airlines" },
  { IATA: "T2", ICAO: "TMA", Name: "TMA Cargo" },
  { IATA: "T3", ICAO: "EZE", Name: "Eastern Airways" },
  { IATA: "T4", ICAO: "HEJ", Name: "Hellas Jet" },
  { IATA: "T6", ICAO: "TVR", Name: "Tavrey Airlines" },
  { IATA: "T7", ICAO: "TJT", Name: "Twin Jet" },
  { IATA: "T9", ICAO: "TSX", Name: "Thai Star Airlines" },
  { IATA: "T9", ICAO: "TRZ", Name: "TransMeridian Airlines" },
  { IATA: "TA", ICAO: "TAI", Name: "Avianca El Salvador" },
  { IATA: "TB", ICAO: "JAF", Name: "TUI fly Belgium" },
  { IATA: "TC", ICAO: "ATC", Name: "Air Tanzania" },
  { IATA: "TD", ICAO: "LUR", Name: "Atlantis European Airways" },
  { IATA: "TD", ICAO: "TLP", Name: "Tulip Air" },
  { IATA: "TE", ICAO: "LIL", Name: "FlyLal" },
  { IATA: "TG", ICAO: "THA", Name: "Thai Airways" },
  { IATA: "TH", ICAO: "TSE", Name: "Transmile Air Services" },
  { IATA: "TI", ICAO: "TOL", Name: "Tol-Air Services" },
  { IATA: "TK", ICAO: "THY", Name: "Turkish Airlines" },
  { IATA: "TL", ICAO: "ANO", Name: "Airnorth" },
  { IATA: "TM", ICAO: "LAM", Name: "LAM Mozambique Airlines" },
  { IATA: "TN", ICAO: "THT", Name: "Air Tahiti Nui" },
  { IATA: "TO", ICAO: "TVF", Name: "Transavia France" },
  { IATA: "TP", ICAO: "TAP", Name: "TAP Air Portugal" },
  { IATA: "TQ", ICAO: "TDM", Name: "Tandem Aero" },
  { IATA: "TR", ICAO: "TGW", Name: "Scoot" },
  { IATA: "TS", ICAO: "TSC", Name: "Air Transat" },
  { IATA: "TT", ICAO: "TGG", Name: "Tigerair Australia" },
  { IATA: "TU", ICAO: "TAR", Name: "Tunisair" },
  { IATA: "TV", ICAO: "VEX", Name: "Virgin Express" },
  { IATA: "TW", ICAO: "TWB", Name: "T'way Air" },
  { IATA: "TX", ICAO: "FWI", Name: "Air Caraïbes" },
  { IATA: "TY", ICAO: "TPC", Name: "Air Calédonie" },
  { IATA: "TZ", ICAO: "AMT", Name: "ATA Airlines" },
  { IATA: "U2", ICAO: "EZY", Name: "easyJet" },
  { IATA: "U3", ICAO: "AIA", Name: "Avies" },
  { IATA: "U4", ICAO: "PMT", Name: "PMTair" },
  { IATA: "U5", ICAO: "GWY", Name: "USA3000 Airlines" },
  { IATA: "U6", ICAO: "SVR", Name: "Ural Airlines" },
  { IATA: "U7", ICAO: "JUS", Name: "USA Jet Airlines" },
  { IATA: "U8", ICAO: "RNV", Name: "Armavia" },
  { IATA: "U9", ICAO: "TAK", Name: "Tatarstan Airlines" },
  { IATA: "UA", ICAO: "UAL", Name: "United Airlines" },
  { IATA: "UB", ICAO: "UBA", Name: "Myanma Airways" },
  { IATA: "UE", ICAO: "NAS", Name: "Nasair" },
  { IATA: "UF", ICAO: "UKM", Name: "UM Airlines" },
  { IATA: "UG", ICAO: "TUX", Name: "Tunisair Express" },
  { IATA: "UI", ICAO: "ECA", Name: "Eurocypria Airlines" },
  { IATA: "UK", ICAO: "VTI", Name: "Vistara" },
  { IATA: "UL", ICAO: "ALK", Name: "SriLankan Airlines" },
  { IATA: "UM", ICAO: "AZW", Name: "Air Zimbabwe" },
  { IATA: "UN", ICAO: "TSO", Name: "Transaero Airlines" },
  { IATA: "UO", ICAO: "HKE", Name: "HK Express" },
  { IATA: "UP", ICAO: "BHS", Name: "Bahamasair" },
  { IATA: "US", ICAO: "AWE", Name: "US Airways" },
  { IATA: "UT", ICAO: "UTA", Name: "UTair Aviation" },
  { IATA: "UU", ICAO: "REU", Name: "Air Austral" },
  { IATA: "UX", ICAO: "AEA", Name: "Air Europa" },
  { IATA: "UY", ICAO: "UYC", Name: "Cameroon Airlines" },
  { IATA: "UZ", ICAO: "BRQ", Name: "El-Buraq Air Transport" },
  { IATA: "V0", ICAO: "VCV", Name: "Conviasa" },
  { IATA: "V2", ICAO: "AKT", Name: "Karat" },
  { IATA: "V3", ICAO: "KRP", Name: "Carpatair" },
  { IATA: "V4", ICAO: "REK", Name: "Reem Air" },
  { IATA: "V5", ICAO: "VLI", Name: "Avolar Aerolineas" },
  { IATA: "V5", ICAO: "RYL", Name: "Royal Aruban Airline" },
  { IATA: "V7", ICAO: "SNG", Name: "Air Senegal International" },
  { IATA: "V8", ICAO: "VAS", Name: "ATRAN Cargo Airlines" },
  { IATA: "V9", ICAO: "BTC", Name: "BAL Bashkirian Airlines" },
  { IATA: "VA", ICAO: "VOZ", Name: "Virgin Australia" },
  { IATA: "VB", ICAO: "VIV", Name: "VivaAerobús" },
  { IATA: "VC", ICAO: "AGC", Name: "Air Australia" },
  { IATA: "VC", ICAO: "VAL", Name: "Voyageur Airways" },
  { IATA: "VD", ICAO: "KPA", Name: "Henan Airlines" },
  { IATA: "VE", ICAO: "EUJ", Name: "EUjet" },
  { IATA: "VE", ICAO: "VLE", Name: "Volare Airlines" },
  { IATA: "VE", ICAO: "AVE", Name: "Avensa" },
  { IATA: "VF", ICAO: "VLU", Name: "Valuair" },
  { IATA: "VG", ICAO: "VLM", Name: "VLM Airlines" },
  { IATA: "VI", ICAO: "VDA", Name: "Volga-Dnepr Airlines" },
  { IATA: "VJ", ICAO: "VJC", Name: "VietJet Air" },
  { IATA: "VK", ICAO: "VGN", Name: "Virgin Nigeria Airways" },
  { IATA: "VL", ICAO: "VIM", Name: "Air VIA" },
  { IATA: "VM", ICAO: "VOA", Name: "Viaggio Air" },
  { IATA: "VN", ICAO: "HVN", Name: "Vietnam Airlines" },
  { IATA: "VO", ICAO: "TYR", Name: "Austrian Arrows" },
  { IATA: "VP", ICAO: "VSP", Name: "VASP" },
  { IATA: "VR", ICAO: "TCV", Name: "TACV" },
  { IATA: "VS", ICAO: "VIR", Name: "Virgin Atlantic Airways" },
  { IATA: "VT", ICAO: "VTA", Name: "Air Tahiti" },
  { IATA: "VU", ICAO: "VUN", Name: "Air Ivoire" },
  { IATA: "VV", ICAO: "AEW", Name: "Aerosvit Airlines" },
  { IATA: "VW", ICAO: "TAO", Name: "Aeromar" },
  { IATA: "VX", ICAO: "VRD", Name: "Virgin America" },
  { IATA: "VY", ICAO: "VLG", Name: "Vueling Airlines" },
  { IATA: "VZ", ICAO: "QCL", Name: "Air Class Lineas Aereas" },
  { IATA: "W1", ICAO: "WDL", Name: "WDL Aviation" },
  { IATA: "W2", ICAO: "CWA", Name: "Canadian Western Airlines" },
  { IATA: "W3", ICAO: "FYH", Name: "Flyhy Cargo Airlines" },
  { IATA: "W4", ICAO: "BES", Name: "Aero Services Executive" },
  { IATA: "W5", ICAO: "IRM", Name: "Mahan Air" },
  { IATA: "W6", ICAO: "WZZ", Name: "Wizz Air" },
  { IATA: "W8", ICAO: "CJT", Name: "Cargojet Airways" },
  { IATA: "W9", ICAO: "WUK", Name: "Wizz Air UK" },
  { IATA: "WA", ICAO: "KLC", Name: "KLM Cityhopper" },
  { IATA: "WB", ICAO: "RWD", Name: "Rwandair Express" },
  { IATA: "WC", ICAO: "ISV", Name: "Islena De Inversiones" },
  { IATA: "WD", ICAO: "DSR", Name: "DAS Air Cargo" },
  { IATA: "WE", ICAO: "CWC", Name: "Centurion Air Cargo" },
  { IATA: "WF", ICAO: "WIF", Name: "Widerøe" },
  { IATA: "WG", ICAO: "SWG", Name: "Sunwing Airlines" },
  { IATA: "WH", ICAO: "CNW", Name: "China Northwest Airlines" },
  { IATA: "WJ", ICAO: "WEB", Name: "WebJet Linhas Aéreas" },
  { IATA: "WK", ICAO: "EDW", Name: "Edelweiss Air" },
  { IATA: "WN", ICAO: "SWA", Name: "Southwest Airlines" },
  { IATA: "WO", ICAO: "WSW", Name: "Swoop" },
  { IATA: "WQ", ICAO: "SWQ", Name: "iAero Airways" },
  { IATA: "WR", ICAO: "HRH", Name: "Royal Tongan Airlines" },
  { IATA: "WS", ICAO: "WJA", Name: "WestJet" },
  { IATA: "WT", ICAO: "WSG", Name: "Wasaya Airways" },
  { IATA: "WV", ICAO: "SWV", Name: "Swe Fly" },
  { IATA: "WW", ICAO: "WOW", Name: "WOW air" },
  { IATA: "WX", ICAO: "BCY", Name: "CityJet" },
  { IATA: "WY", ICAO: "OMA", Name: "Oman Air" },
  { IATA: "WZ", ICAO: "WSF", Name: "West African Airlines" },
  { IATA: "X3", ICAO: "TUI", Name: "TUI fly Deutschland" },
  { IATA: "X7", ICAO: "CHF", Name: "Chitaavia" },
  { IATA: "X9", ICAO: "NVD", Name: "Avion Express" },
  { IATA: "XC", ICAO: "CAI", Name: "Corendon Airlines" },
  { IATA: "XE", ICAO: "JSX", Name: "JSX" },
  { IATA: "XF", ICAO: "VLK", Name: "Vladivostok Air" },
  { IATA: "XG", ICAO: "CLI", Name: "Clickair" },
  { IATA: "XJ", ICAO: "MES", Name: "Mesaba Airlines" },
  { IATA: "XK", ICAO: "CCM", Name: "Corse-Mediterranee" },
  { IATA: "XL", ICAO: "LNE", Name: "LATAM Ecuador" },
  { IATA: "XO", ICAO: "LTE", Name: "LTE International Airways" },
  { IATA: "XO", ICAO: "CXH", Name: "China Xinhua Airlines" },
  { IATA: "XP", ICAO: "VXP", Name: "Avelo Airlines" },
  { IATA: "XQ", ICAO: "SXS", Name: "SunExpress" },
  { IATA: "XS", ICAO: "SIT", Name: "SITA" },
  { IATA: "XT", ICAO: "AXL", Name: "Air Exel" },
  { IATA: "XW", ICAO: "NCT", Name: "NokScoot" },
  { IATA: "XY", ICAO: "KNE", Name: "flynas" },
  { IATA: "Y4", ICAO: "VOI", Name: "Volaris" },
  { IATA: "Y5", ICAO: "PCE", Name: "Pace Airlines" },
  { IATA: "Y8", ICAO: "YZR", Name: "Suparna Airlines" },
  { IATA: "Y9", ICAO: "IRK", Name: "Kish Air" },
  { IATA: "YG", ICAO: "HYT", Name: "YTO Cargo Airlines" },
  { IATA: "YH", ICAO: "WCW", Name: "West Caribbean Airways" },
  { IATA: "YI", ICAO: "RSI", Name: "Air Sunshine" },
  { IATA: "YL", ICAO: "LLM", Name: "Yamal Airlines" },
  { IATA: "YM", ICAO: "MGX", Name: "Montenegro Airlines" },
  { IATA: "YP", ICAO: "APZ", Name: "Air Premia" },
  { IATA: "YT", ICAO: "TGA", Name: "Air Togo" },
  { IATA: "YU", ICAO: "MMZ", Name: "EuroAtlantic Airways" },
  { IATA: "YV", ICAO: "ASH", Name: "Mesa Airlines" },
  { IATA: "YW", ICAO: "ANE", Name: "Air Nostrum" },
  { IATA: "YX", ICAO: "MEP", Name: "Midwest Airlines" },
  { IATA: "Z2", ICAO: "EZD", Name: "AirAsia Zest" },
  { IATA: "Z3", ICAO: "SMJ", Name: "Avient Aviation" },
  { IATA: "Z4", ICAO: "OOM", Name: "Zoom Airlines" },
  { IATA: "Z7", ICAO: "ADK", Name: "ADC Airlines" },
  { IATA: "Z8", ICAO: "AZN", Name: "Amaszonas" },
  { IATA: "Z9", ICAO: "BEK", Name: "Bek Air" },
  { IATA: "ZA", ICAO: "SUW", Name: "Interavia Airlines" },
  { IATA: "ZA", ICAO: "CYD", Name: "Access Air" },
  { IATA: "ZB", ICAO: "BUB", Name: "Air Bourbon" },
  { IATA: "ZB", ICAO: "MON", Name: "Monarch Airlines" },
  { IATA: "ZE", ICAO: "AZE", Name: "Arcus-Air Logistic" },
  { IATA: "ZE", ICAO: "LCD", Name: "Lineas Aereas Azteca" },
  { IATA: "ZH", ICAO: "CSZ", Name: "Shenzhen Airlines" },
  { IATA: "ZI", ICAO: "AAF", Name: "Aigle Azur" },
  { IATA: "ZK", ICAO: "GLA", Name: "Great Lakes Airlines" },
  { IATA: "ZL", ICAO: "RXA", Name: "Regional Express" },
  { IATA: "ZP", ICAO: "AZQ", Name: "Silk Way Airlines" },
  { IATA: "ZS", ICAO: "AZI", Name: "Azzurra Air" },
  { IATA: "ZS", ICAO: "SMY", Name: "Sama Airlines" },
  { IATA: "ZT", ICAO: "AWC", Name: "Titan Airways" },
  { IATA: "ZU", ICAO: "HCY", Name: "Helios Airways" },
  { IATA: "ZV", ICAO: "AMW", Name: "Air Midwest" },
  { IATA: "ZW", ICAO: "AWI", Name: "Air Wisconsin" },
  { IATA: "ZX", ICAO: "GGN", Name: "Air Georgian" },
  { IATA: "04", ICAO: "ABV", Name: "Antrak Air" },
  { IATA: "0A", ICAO: "GNT", Name: "Amber Air" },
  { IATA: "0B", ICAO: "BMS", Name: "Blue Air" },
  { IATA: "0D", ICAO: "DWT", Name: "Darwin Airline" },
  { IATA: "0J", ICAO: "JCS", Name: "Jetclub" },
  { IATA: "1A", ICAO: "AGT", Name: "Amadeus Global Travel Distribution" },
  { IATA: "1I", ICAO: "EJA", Name: "NetJets" },
  { IATA: "1L", ICAO: "OSY", Name: "Open Skies Consultative Commission" },
  { IATA: "1T", ICAO: "RNX", Name: "1Time Airline" },
  { IATA: "1W", ICAO: "WON", Name: "Wings Air" },
  { IATA: "20", ICAO: "RNE", Name: "Air Salone" },
  { IATA: "2B", ICAO: "ARD", Name: "Aerocondor" },
  { IATA: "2D", ICAO: "EAL", Name: "Eastern Airlines" },
  { IATA: "2F", ICAO: "FTA", Name: "Frontier Flying Service" },
  { IATA: "2G", ICAO: "CRG", Name: "Cargoitalia" },
  { IATA: "2J", ICAO: "VBW", Name: "Air Burkina" },
  { IATA: "2K", ICAO: "GLG", Name: "Aerogal" },
  { IATA: "2L", ICAO: "OAW", Name: "Helvetic Airways" },
  { IATA: "2M", ICAO: "MDV", Name: "Moldavian Airlines" },
  { IATA: "2N", ICAO: "UMK", Name: "Yuzhmashavia" },
  { IATA: "2P", ICAO: "GAP", Name: "Air Philippines" },
  { IATA: "2Q", ICAO: "SNC", Name: "Air Cargo Carriers" },
  { IATA: "2S", ICAO: "SDY", Name: "Island Express" },
  { IATA: "2T", ICAO: "HAM", Name: "Haiti Ambassador Airlines" },
  { IATA: "2U", ICAO: "GIP", Name: "Air Guinee Express" },
  { IATA: "2W", ICAO: "WLC", Name: "Welcome Air" },
  { IATA: "2Z", ICAO: "CGN", Name: "Changan Airlines" },
  { IATA: "3C", ICAO: "CVA", Name: "Air Chathams" },
  { IATA: "3G", ICAO: "AYZ", Name: "Atlant-Soyuz Airlines" },
  { IATA: "3H", ICAO: "AIE", Name: "Air Inuit" },
  { IATA: "3J", ICAO: "WZP", Name: "Zip" },
  { IATA: "3K", ICAO: "JSA", Name: "Jetstar Asia Airways" },
  { IATA: "3M", ICAO: "GFT", Name: "Gulfstream International Airlines" },
  { IATA: "3N", ICAO: "URG", Name: "Air Urga" },
  { IATA: "3P", ICAO: "TNM", Name: "Tiara Air" },
  { IATA: "3Q", ICAO: "CYH", Name: "Yunnan Airlines" },
  { IATA: "3R", ICAO: "GAI", Name: "Moskovia Airlines" },
  { IATA: "3S", ICAO: "AEN", Name: "Aeroland Airways" },
  { IATA: "3T", ICAO: "URN", Name: "Turan Air" },
  { IATA: "3U", ICAO: "CSC", Name: "Sichuan Airlines" },
  { IATA: "3V", ICAO: "TAY", Name: "ASL Airlines Belgium" },
  { IATA: "3W", ICAO: "EMX", Name: "Euromanx Airways" },
  { IATA: "4A", ICAO: "AKL", Name: "Air Kiribati" },
  {
    IATA: "4C",
    ICAO: "ARE",
    Name: "Aires, Aerovias de Integracion Regional, S.A.",
  },
  { IATA: "4D", ICAO: "ASD", Name: "Air Sinai" },
  { IATA: "4F", ICAO: "ECE", Name: "Air City" },
  { IATA: "4G", ICAO: "GZP", Name: "Gazpromavia" },
  { IATA: "4I", ICAO: "KNX", Name: "Knighthawk Air Express" },
  { IATA: "4J", ICAO: "SMR", Name: "Somon Air" },
  { IATA: "4K", ICAO: "AAS", Name: "Askari Aviation" },
  { IATA: "4L", ICAO: "LAU", Name: "Líneas Aéreas Suramericanas" },
  { IATA: "4M", ICAO: "DSM", Name: "Aero 2000" },
  { IATA: "4N", ICAO: "ANT", Name: "Air North Charter - Canada" },
  { IATA: "4O", ICAO: "AIJ", Name: "Interjet" },
  { IATA: "4R", ICAO: "HHI", Name: "Hamburg International" },
  { IATA: "4S", ICAO: "FNC", Name: "Finalair Congo" },
  { IATA: "4T", ICAO: "BHP", Name: "Belair Airlines" },
  { IATA: "4U", ICAO: "GWI", Name: "Germanwings" },
  { IATA: "4Y", ICAO: "RBU", Name: "Airbus France" },
  { IATA: "5A", ICAO: "AIP", Name: "Alpine Air Express" },
  { IATA: "5C", ICAO: "ICL", Name: "CAL Cargo Air Lines" },
  { IATA: "5D", ICAO: "SLI", Name: "Aerolitoral" },
  { IATA: "5D", ICAO: "UDC", Name: "DonbassAero" },
  { IATA: "5F", ICAO: "CIR", Name: "Arctic Circle Air Service" },
  { IATA: "5G", ICAO: "SSV", Name: "Skyservice Airlines" },
  { IATA: "5J", ICAO: "CEB", Name: "Cebu Pacific" },
  { IATA: "5K", ICAO: "HFY", Name: "Hi Fly" },
  { IATA: "5L", ICAO: "RSU", Name: "Aerosur" },
  { IATA: "5M", ICAO: "SIB", Name: "Sibaviatrans" },
  { IATA: "5N", ICAO: "AUL", Name: "Aeroflot-Nord" },
  { IATA: "5O", ICAO: "FPO", Name: "ASL Airlines France" },
  { IATA: "5T", ICAO: "MPE", Name: "Canadian North" },
  { IATA: "5V", ICAO: "UKW", Name: "Lviv Airlines" },
  { IATA: "5W", ICAO: "AEU", Name: "Astraeus" },
  { IATA: "5X", ICAO: "UPS", Name: "UPS Airlines" },
  { IATA: "5Y", ICAO: "GTI", Name: "Atlas Air" },
  { IATA: "5Z", ICAO: "BML", Name: "Bismillah Airlines" },
  { IATA: "6A", ICAO: "CHP", Name: "Consorcio Aviaxsa" },
  { IATA: "6B", ICAO: "BLX", Name: "TUI fly Nordic" },
  { IATA: "6E", ICAO: "IGO", Name: "IndiGo" },
  { IATA: "6G", ICAO: "AWW", Name: "Air Wales" },
  { IATA: "6H", ICAO: "ISR", Name: "Israir" },
  { IATA: "6I", ICAO: "IBZ", Name: "International Business Air" },
  { IATA: "6J", ICAO: "SNJ", Name: "Solaseed Air" },
  { IATA: "6K", ICAO: "RIT", Name: "Asian Spirit" },
  { IATA: "6N", ICAO: "NRD", Name: "Nordic Regional" },
  { IATA: "6P", ICAO: "ISG", Name: "Club Air" },
  { IATA: "6Q", ICAO: "SLL", Name: "Slovak Airlines" },
  { IATA: "6R", ICAO: "DRU", Name: "Alrosa Mirny Air Enterprise" },
  { IATA: "6R*", ICAO: "TNO", Name: "AeroUnion" },
  { IATA: "6U", ICAO: "UKR", Name: "Air Ukraine" },
  { IATA: "6V", ICAO: "AXY", Name: "Axis Airways" },
  { IATA: "6V", ICAO: "MRW", Name: "Mars RK" },
  { IATA: "6V", ICAO: "VGA", Name: "Air Vegas" },
  { IATA: "6W", ICAO: "SOV", Name: "Saratov Aviation Division" },
  { IATA: "6Z", ICAO: "UKS", Name: "Ukrainian Cargo Airways" },
  { IATA: "7B", ICAO: "KJC", Name: "Krasnojarsky Airlines" },
  { IATA: "7C", ICAO: "JJA", Name: "Jeju Air" },
  { IATA: "7C*", ICAO: "COY", Name: "Coyne Airways" },
  { IATA: "7E", ICAO: "AWU", Name: "Aeroline GmbH" },
  { IATA: "7F", ICAO: "FAB", Name: "First Air" },
  { IATA: "7G", ICAO: "SFJ", Name: "StarFlyer" },
  { IATA: "7H", ICAO: "RVF", Name: "Ravn Alaska" },
  { IATA: "7K", ICAO: "KGL", Name: "Kogalymavia Air Company" },
  { IATA: "7L", ICAO: "AZG", Name: "Silk Way West Airlines" },
  { IATA: "7M", ICAO: "MSA", Name: "Mistral Air" },
  { IATA: "7N", ICAO: "CNA", Name: "Centavia" },
  { IATA: "7O", ICAO: "GAL", Name: "Galaxy Air" },
  { IATA: "7P", ICAO: "BTV", Name: "Metro Batavia" },
  { IATA: "7R", ICAO: "BRB", Name: "BRA-Transportes Aereos" },
  { IATA: "7T", ICAO: "AGV", Name: "Air Glaciers" },
  { IATA: "7T", ICAO: "TOB", Name: "Tobruk Air" },
  { IATA: "7W", ICAO: "WAY", Name: "Wayraperú" },
  { IATA: "8A", ICAO: "BMM", Name: "Atlas Blue" },
  { IATA: "8B", ICAO: "GFI", Name: "Caribbean Star Airlines" },
  { IATA: "8C", ICAO: "ATN", Name: "Air Transport International" },
  { IATA: "8D", ICAO: "EXV", Name: "Expo Aviation" },
  { IATA: "8E", ICAO: "BRG", Name: "Bering Air" },
  { IATA: "8F", ICAO: "FFR", Name: "Fischer Air" },
  { IATA: "8H", ICAO: "HFR", Name: "Heli France" },
  { IATA: "8J", ICAO: "KMV", Name: "Komiinteravia" },
  { IATA: "8L", ICAO: "CGP", Name: "Cargo Plus Aviation" },
  { IATA: "8L", ICAO: "RHC", Name: "Redhill Aviation" },
  { IATA: "8M", ICAO: "MXL", Name: "Maxair" },
  { IATA: "8N", ICAO: "NKF", Name: "Barents AirLink" },
  { IATA: "8P", ICAO: "PCO", Name: "Pacific Coastal Airline" },
  { IATA: "8Q", ICAO: "OHY", Name: "Onur Air" },
  { IATA: "8T", ICAO: "TID", Name: "Air Tindi" },
  { IATA: "8U", ICAO: "AAW", Name: "Afriqiyah Airways" },
  { IATA: "8V", ICAO: "ACP", Name: "Astral Aviation" },
  { IATA: "8V", ICAO: "WRF", Name: "Wright Air Service" },
  { IATA: "8W", ICAO: "PWF", Name: "Private Wings Flugcharter" },
  { IATA: "8Y", ICAO: "PBU", Name: "Air Burundi" },
  {
    IATA: "8z",
    ICAO: "LER",
    Name: "Linea Aerea de Servicio Ejecutivo Regional",
  },
  { IATA: "9C", ICAO: "CQH", Name: "Spring Airlines" },
  { IATA: "9E", ICAO: "EDV", Name: "Endeavor Air" },
  { IATA: "9H", ICAO: "DNL", Name: "Dutch Antilles Express" },
  { IATA: "9I", ICAO: "LLR", Name: "Alliance Air" },
  { IATA: "9K", ICAO: "KAP", Name: "Cape Air" },
  { IATA: "9L", ICAO: "CJC", Name: "Colgan Air" },
  { IATA: "9Q", ICAO: "PBA", Name: "PB Air" },
  { IATA: "9R", ICAO: "VAP", Name: "Phuket Air" },
  { IATA: "9S", ICAO: "SOO", Name: "Southern Air" },
  { IATA: "9T", ICAO: "ABS", Name: "Transwest Air" },
  { IATA: "9T", ICAO: "RUN", Name: "Air ACT" },
  { IATA: "9U", ICAO: "MLD", Name: "Air Moldova" },
  { IATA: "9W", ICAO: "JAI", Name: "Jet Airways" },
  { IATA: "9X", ICAO: "ACL", Name: "Itali Airlines" },
];
